class Config():
    num_epochs = 1
    validation_summary_frequency = 1000
    checkpoint_frequency = 1000
    batch_size = 32
    log_directory = '../logs/Autoencoder/'
    examples_to_show = 5
    val_size = 5
    train_image_size = 400 # train images are of size 400 x 400
    test_image_size = 608 # test images are of size 608 x 608
    cnn_res = 16
    gt_res = 8
    train_size = 5 # train data set size
    test_size = 5 # test data set size
    patch_size = 24
    dropout_train = 1.0
    learning_rate = 0.005
    ae_step = 8
    corruption = 0.075
    visualise_validation = True
    run_on_test_set = True
    run_on_train_set = True
